// Types conformes au modèle CategoriesPost
export type Category = {
  id: string;
  order: number;
  label: string;
  img?: string | null;
  parentId?: string | null;
  children?: Category[]; // pour la hiérarchie
  posts?: any[]; // simulé
};

export const mockCategories: Category[] = [
  {
    id: "cat-tech",
    order: 1,
    label: "Technologies",
    img: "💻",
    children: [
      {
        id: "cat-prog",
        order: 1,
        label: "Programmation",
        img: "👨‍💻",
        parentId: "cat-tech",
        children: [
          {
            id: "cat-lang",
            order: 1,
            label: "Langages",
            img: "🔤",
            parentId: "cat-prog",
            posts: [],
          },
          {
            id: "cat-framework",
            order: 2,
            label: "Frameworks",
            img: "⚛️",
            parentId: "cat-prog",
            posts: [{}],
          },
          {
            id: "cat-db",
            order: 3,
            label: "Bases de données",
            img: "🗄️",
            parentId: "cat-prog",
            posts: [{}],
          },
        ],
      },
      {
        id: "cat-ai",
        order: 2,
        label: "Intelligence Artificielle",
        img: "🤖",
        parentId: "cat-tech",
        children: [
          {
            id: "cat-ml",
            order: 1,
            label: "Machine Learning",
            img: "📊",
            parentId: "cat-ai",
          },
          {
            id: "cat-dl",
            order: 2,
            label: "Deep Learning",
            img: "🧠",
            parentId: "cat-ai",
          },
          {
            id: "cat-nlp",
            order: 3,
            label: "Traitement du langage",
            img: "🗣️",
            parentId: "cat-ai",
          },
        ],
      },
      {
        id: "cat-cyber",
        order: 3,
        label: "Cybersécurité",
        img: "🔒",
        parentId: "cat-tech",
        children: [
          {
            id: "cat-hack",
            order: 1,
            label: "Ethical Hacking",
            img: "🕵️",
            parentId: "cat-cyber",
          },
          {
            id: "cat-network",
            order: 2,
            label: "Sécurité réseau",
            img: "🌐",
            parentId: "cat-cyber",
          },
        ],
      },
      {
        id: "cat-webdesign",
        order: 4,
        label: "Web Design",
        img: "🎨",
        parentId: "cat-tech",
        children: [
          {
            id: "cat-ui",
            order: 1,
            label: "UI/UX",
            img: "✨",
            parentId: "cat-webdesign",
          },
          {
            id: "cat-tools",
            order: 2,
            label: "Outils (Figma, etc.)",
            img: "🛠️",
            parentId: "cat-webdesign",
          },
        ],
      },
    ],
  },
  {
    id: "cat-travel",
    order: 2,
    label: "Voyages",
    img: "✈️",
    children: [
      {
        id: "cat-dest",
        order: 1,
        label: "Destinations",
        img: "🗺️",
        parentId: "cat-travel",
        children: [
          {
            id: "cat-europe",
            order: 1,
            label: "Europe",
            img: "🇪🇺",
            parentId: "cat-dest",
          },
          {
            id: "cat-asia",
            order: 2,
            label: "Asie",
            img: "🇯🇵",
            parentId: "cat-dest",
          },
          {
            id: "cat-america",
            order: 3,
            label: "Amériques",
            img: "🇺🇸",
            parentId: "cat-dest",
          },
          {
            id: "cat-africa",
            order: 4,
            label: "Afrique",
            img: "🌍",
            parentId: "cat-dest",
          },
        ],
      },
      {
        id: "cat-tips",
        order: 2,
        label: "Conseils pratiques",
        img: "💡",
        parentId: "cat-travel",
        children: [
          {
            id: "cat-budget",
            order: 1,
            label: "Budget et économies",
            img: "💰",
            parentId: "cat-tips",
          },
          {
            id: "cat-gear",
            order: 2,
            label: "Matériel de voyage",
            img: "🎒",
            parentId: "cat-tips",
          },
        ],
      },
      {
        id: "cat-stories",
        order: 3,
        label: "Récits de voyage",
        img: "📖",
        parentId: "cat-travel",
      },
    ],
  },
  {
    id: "cat-food",
    order: 3,
    label: "Cuisine",
    img: "🍳",
    children: [
      {
        id: "cat-recipes",
        order: 1,
        label: "Recettes",
        img: "📝",
        parentId: "cat-food",
        children: [
          {
            id: "cat-starters",
            order: 1,
            label: "Entrées",
            img: "🥗",
            parentId: "cat-recipes",
          },
          {
            id: "cat-main",
            order: 2,
            label: "Plats",
            img: "🍲",
            parentId: "cat-recipes",
          },
          {
            id: "cat-desserts",
            order: 3,
            label: "Desserts",
            img: "🍰",
            parentId: "cat-recipes",
          },
        ],
      },
      {
        id: "cat-techniques",
        order: 2,
        label: "Techniques culinaires",
        img: "🔪",
        parentId: "cat-food",
        children: [
          {
            id: "cat-baking",
            order: 1,
            label: "Pâtisserie",
            img: "🥐",
            parentId: "cat-techniques",
          },
          {
            id: "cat-knife",
            order: 2,
            label: "Découpe",
            img: "🔪",
            parentId: "cat-techniques",
          },
        ],
      },
    ],
  },
  {
    id: "cat-fashion",
    order: 4,
    label: "Mode & Beauté",
    img: "👗",
    children: [
      {
        id: "cat-trends",
        order: 1,
        label: "Tendances",
        img: "✨",
        parentId: "cat-fashion",
      },
      {
        id: "cat-makeup",
        order: 2,
        label: "Maquillage",
        img: "💄",
        parentId: "cat-fashion",
        children: [
          {
            id: "cat-eye",
            order: 1,
            label: "Yeux",
            img: "👁️",
            parentId: "cat-makeup",
          },
          {
            id: "cat-lip",
            order: 2,
            label: "Lèvres",
            img: "💋",
            parentId: "cat-makeup",
          },
        ],
      },
      {
        id: "cat-skincare",
        order: 3,
        label: "Soins",
        img: "🧴",
        parentId: "cat-fashion",
      },
    ],
  },
  {
    id: "cat-health",
    order: 5,
    label: "Santé & Bien-être",
    img: "🧘",
    children: [
      {
        id: "cat-nutrition",
        order: 1,
        label: "Nutrition",
        img: "🥦",
        parentId: "cat-health",
      },
      {
        id: "cat-fitness",
        order: 2,
        label: "Fitness",
        img: "💪",
        parentId: "cat-health",
        children: [
          {
            id: "cat-yoga",
            order: 1,
            label: "Yoga",
            img: "🧘‍♀️",
            parentId: "cat-fitness",
          },
          {
            id: "cat-cardio",
            order: 2,
            label: "Cardio",
            img: "🏃",
            parentId: "cat-fitness",
          },
        ],
      },
      {
        id: "cat-mental",
        order: 3,
        label: "Santé mentale",
        img: "🧠",
        parentId: "cat-health",
      },
    ],
  },
  {
    id: "cat-finance",
    order: 6,
    label: "Finance personnelle",
    img: "💰",
    children: [
      {
        id: "cat-budgeting",
        order: 1,
        label: "Budget",
        img: "📊",
        parentId: "cat-finance",
      },
      {
        id: "cat-invest",
        order: 2,
        label: "Investissements",
        img: "📈",
        parentId: "cat-finance",
        children: [
          {
            id: "cat-stocks",
            order: 1,
            label: "Actions",
            img: "📉",
            parentId: "cat-invest",
          },
          {
            id: "cat-realestate",
            order: 2,
            label: "Immobilier",
            img: "🏠",
            parentId: "cat-invest",
          },
        ],
      },
      {
        id: "cat-savings",
        order: 3,
        label: "Épargne",
        img: "🏦",
        parentId: "cat-finance",
      },
    ],
  },
  {
    id: "cat-education",
    order: 7,
    label: "Éducation",
    img: "📚",
    children: [
      {
        id: "cat-languages",
        order: 1,
        label: "Langues",
        img: "🗣️",
        parentId: "cat-education",
        children: [
          {
            id: "cat-english",
            order: 1,
            label: "Anglais",
            img: "🇬🇧",
            parentId: "cat-languages",
          },
          {
            id: "cat-spanish",
            order: 2,
            label: "Espagnol",
            img: "🇪🇸",
            parentId: "cat-languages",
          },
        ],
      },
      {
        id: "cat-methods",
        order: 2,
        label: "Méthodologie",
        img: "✏️",
        parentId: "cat-education",
      },
      {
        id: "cat-career",
        order: 3,
        label: "Orientation",
        img: "🎓",
        parentId: "cat-education",
      },
    ],
  },
  {
    id: "cat-culture",
    order: 8,
    label: "Culture",
    img: "🎭",
    children: [
      {
        id: "cat-cinema",
        order: 1,
        label: "Cinéma",
        img: "🎬",
        parentId: "cat-culture",
        children: [
          {
            id: "cat-reviews",
            order: 1,
            label: "Critiques",
            img: "⭐",
            parentId: "cat-cinema",
          },
          {
            id: "cat-directors",
            order: 2,
            label: "Réalisateurs",
            img: "🎥",
            parentId: "cat-cinema",
          },
        ],
      },
      {
        id: "cat-music",
        order: 2,
        label: "Musique",
        img: "🎵",
        parentId: "cat-culture",
      },
      {
        id: "cat-books",
        order: 3,
        label: "Livres",
        img: "📖",
        parentId: "cat-culture",
      },
    ],
  },
  {
    id: "cat-lifestyle",
    order: 9,
    label: "Lifestyle",
    img: "🌟",
    children: [
      {
        id: "cat-home",
        order: 1,
        label: "Maison & Décoration",
        img: "🏡",
        parentId: "cat-lifestyle",
      },
      {
        id: "cat-parenting",
        order: 2,
        label: "Parentalité",
        img: "👶",
        parentId: "cat-lifestyle",
        children: [
          {
            id: "cat-babies",
            order: 1,
            label: "Bébés",
            img: "🍼",
            parentId: "cat-parenting",
          },
          {
            id: "cat-teens",
            order: 2,
            label: "Adolescents",
            img: "🧑",
            parentId: "cat-parenting",
          },
        ],
      },
      {
        id: "cat-selfdev",
        order: 3,
        label: "Développement personnel",
        img: "🚀",
        parentId: "cat-lifestyle",
      },
    ],
  },
];
/*

// Types conformes au modèle Prisma CategoriesPost
export type Category = {
  id: string;
  order: number;
  label: string;
  img?: string | null;
  parentId?: string | null;
  children?: Category[];
  posts?: any[];
};

// ================================================
// TAXONOMIE UNIVERSELLE – 3 NIVEAUX
// 20 catégories principales, 100+ sous-catégories, 300+ sous-sous-catégories
// ================================================
export const blogTaxonomy: Category[] = [
  {
    id: "tech",
    order: 1,
    label: "Technologies",
    img: "💻",
    children: [
      {
        id: "dev",
        order: 1,
        label: "Développement",
        img: "👨‍💻",
        parentId: "tech",
        children: [
          { id: "lang", order: 1, label: "Langages", img: "🔤", parentId: "dev" },
          { id: "frameworks", order: 2, label: "Frameworks", img: "⚛️", parentId: "dev" },
          { id: "web", order: 3, label: "Web", img: "🌐", parentId: "dev" },
          { id: "mobile", order: 4, label: "Mobile", img: "📱", parentId: "dev" },
          { id: "desktop", order: 5, label: "Desktop", img: "🖥️", parentId: "dev" },
          { id: "devops", order: 6, label: "DevOps", img: "⚙️", parentId: "dev" },
          { id: "db", order: 7, label: "Bases de données", img: "🗄️", parentId: "dev" },
        ],
      },
      {
        id: "ai",
        order: 2,
        label: "Intelligence Artificielle",
        img: "🤖",
        parentId: "tech",
        children: [
          { id: "ml", order: 1, label: "Machine Learning", img: "📊", parentId: "ai" },
          { id: "dl", order: 2, label: "Deep Learning", img: "🧠", parentId: "ai" },
          { id: "nlp", order: 3, label: "Traitement du langage", img: "🗣️", parentId: "ai" },
          { id: "cv", order: 4, label: "Vision par ordinateur", img: "👁️", parentId: "ai" },
          { id: "genai", order: 5, label: "IA générative", img: "🎨", parentId: "ai" },
        ],
      },
      {
        id: "cyber",
        order: 3,
        label: "Cybersécurité",
        img: "🔒",
        parentId: "tech",
        children: [
          { id: "hack", order: 1, label: "Ethical Hacking", img: "🕵️", parentId: "cyber" },
          { id: "networksec", order: 2, label: "Sécurité réseau", img: "🌐", parentId: "cyber" },
          { id: "appsec", order: 3, label: "Sécurité applicative", img: "📱", parentId: "cyber" },
          { id: "crypto", order: 4, label: "Cryptographie", img: "🔐", parentId: "cyber" },
          { id: "privacy", order: 5, label: "Vie privée", img: "🛡️", parentId: "cyber" },
        ],
      },
      {
        id: "it",
        order: 4,
        label: "Infrastructure & Systèmes",
        img: "🖧",
        parentId: "tech",
        children: [
          { id: "cloud", order: 1, label: "Cloud", img: "☁️", parentId: "it" },
          { id: "sysadmin", order: 2, label: "Administration système", img: "🖥️", parentId: "it" },
          { id: "networks", order: 3, label: "Réseaux", img: "📡", parentId: "it" },
          { id: "iot", order: 4, label: "IoT", img: "📶", parentId: "it" },
        ],
      },
      {
        id: "data",
        order: 5,
        label: "Data Science",
        img: "📈",
        parentId: "tech",
        children: [
          { id: "analytics", order: 1, label: "Analyse de données", img: "📊", parentId: "data" },
          { id: "bigdata", order: 2, label: "Big Data", img: "🗃️", parentId: "data" },
          { id: "viz", order: 3, label: "Visualisation", img: "📉", parentId: "data" },
          { id: "bi", order: 4, label: "Business Intelligence", img: "📋", parentId: "data" },
        ],
      },
    ],
  },
  {
    id: "science",
    order: 2,
    label: "Sciences",
    img: "🔬",
    children: [
      {
        id: "physics",
        order: 1,
        label: "Physique",
        img: "⚛️",
        parentId: "science",
        children: [
          { id: "quantum", order: 1, label: "Quantique", img: "🌀", parentId: "physics" },
          { id: "astro", order: 2, label: "Astrophysique", img: "🌌", parentId: "physics" },
          { id: "mechanics", order: 3, label: "Mécanique", img: "⚙️", parentId: "physics" },
          { id: "particle", order: 4, label: "Particules", img: "💥", parentId: "physics" },
        ],
      },
      {
        id: "biology",
        order: 2,
        label: "Biologie",
        img: "🧬",
        parentId: "science",
        children: [
          { id: "genetics", order: 1, label: "Génétique", img: "🧬", parentId: "biology" },
          { id: "ecology", order: 2, label: "Écologie", img: "🌿", parentId: "biology" },
          { id: "neuroscience", order: 3, label: "Neurosciences", img: "🧠", parentId: "biology" },
          { id: "microbio", order: 4, label: "Microbiologie", img: "🦠", parentId: "biology" },
        ],
      },
      {
        id: "chemistry",
        order: 3,
        label: "Chimie",
        img: "🧪",
        parentId: "science",
        children: [
          { id: "organic", order: 1, label: "Organique", img: "🧴", parentId: "chemistry" },
          { id: "inorganic", order: 2, label: "Inorganique", img: "⚗️", parentId: "chemistry" },
          { id: "biochem", order: 3, label: "Biochimie", img: "🧫", parentId: "chemistry" },
        ],
      },
      {
        id: "math",
        order: 4,
        label: "Mathématiques",
        img: "📐",
        parentId: "science",
        children: [
          { id: "algebra", order: 1, label: "Algèbre", img: "➕", parentId: "math" },
          { id: "geo", order: 2, label: "Géométrie", img: "📏", parentId: "math" },
          { id: "analysis", order: 3, label: "Analyse", img: "∫", parentId: "math" },
          { id: "stats", order: 4, label: "Statistiques", img: "📊", parentId: "math" },
        ],
      },
      {
        id: "space",
        order: 5,
        label: "Astronomie & Espace",
        img: "🚀",
        parentId: "science",
        children: [
          { id: "planets", order: 1, label: "Planètes", img: "🪐", parentId: "space" },
          { id: "stars", order: 2, label: "Étoiles", img: "✨", parentId: "space" },
          { id: "spacex", order: 3, label: "Exploration spatiale", img: "🛰️", parentId: "space" },
        ],
      },
    ],
  },
  {
    id: "health",
    order: 3,
    label: "Santé & Bien-être",
    img: "❤️",
    children: [
      {
        id: "medecine",
        order: 1,
        label: "Médecine",
        img: "🏥",
        parentId: "health",
        children: [
          { id: "cardio", order: 1, label: "Cardiologie", img: "❤️", parentId: "medecine" },
          { id: "neuro", order: 2, label: "Neurologie", img: "🧠", parentId: "medecine" },
          { id: "pediatrics", order: 3, label: "Pédiatrie", img: "👶", parentId: "medecine" },
          { id: "dermato", order: 4, label: "Dermatologie", img: "🧴", parentId: "medecine" },
          { id: "prevention", order: 5, label: "Prévention", img: "🩺", parentId: "medecine" },
        ],
      },
      {
        id: "fitness",
        order: 2,
        label: "Fitness & Sport",
        img: "💪",
        parentId: "health",
        children: [
          { id: "workouts", order: 1, label: "Exercices", img: "🏋️", parentId: "fitness" },
          { id: "yoga", order: 2, label: "Yoga", img: "🧘", parentId: "fitness" },
          { id: "running", order: 3, label: "Course", img: "🏃", parentId: "fitness" },
          { id: "musculation", order: 4, label: "Musculation", img: "🏋️‍♂️", parentId: "fitness" },
        ],
      },
      {
        id: "nutrition",
        order: 3,
        label: "Nutrition & Alimentation",
        img: "🥗",
        parentId: "health",
        children: [
          { id: "diets", order: 1, label: "Régimes", img: "🥑", parentId: "nutrition" },
          { id: "supplements", order: 2, label: "Compléments", img: "💊", parentId: "nutrition" },
          { id: "superfoods", order: 3, label: "Super-aliments", img: "🍓", parentId: "nutrition" },
          { id: "foodscience", order: 4, label: "Sciences des aliments", img: "🔬", parentId: "nutrition" },
        ],
      },
      {
        id: "mental",
        order: 4,
        label: "Santé mentale",
        img: "🧠",
        parentId: "health",
        children: [
          { id: "stress", order: 1, label: "Gestion du stress", img: "😌", parentId: "mental" },
          { id: "anxiety", order: 2, label: "Anxiété", img: "😰", parentId: "mental" },
          { id: "depression", order: 3, label: "Dépression", img: "😔", parentId: "mental" },
          { id: "mindfulness", order: 4, label: "Méditation", img: "🧘", parentId: "mental" },
        ],
      },
      {
        id: "beauty",
        order: 5,
        label: "Beauté & Soins",
        img: "💄",
        parentId: "health",
        children: [
          { id: "skincare", order: 1, label: "Soin de la peau", img: "🧴", parentId: "beauty" },
          { id: "haircare", order: 2, label: "Soin des cheveux", img: "💇", parentId: "beauty" },
          { id: "makeup", order: 3, label: "Maquillage", img: "💋", parentId: "beauty" },
        ],
      },
    ],
  },
  {
    id: "arts",
    order: 4,
    label: "Arts & Culture",
    img: "🎨",
    children: [
      {
        id: "visualarts",
        order: 1,
        label: "Arts visuels",
        img: "🖼️",
        parentId: "arts",
        children: [
          { id: "painting", order: 1, label: "Peinture", img: "🎨", parentId: "visualarts" },
          { id: "sculpture", order: 2, label: "Sculpture", img: "🗿", parentId: "visualarts" },
          { id: "photo", order: 3, label: "Photographie", img: "📷", parentId: "visualarts" },
          { id: "digitalart", order: 4, label: "Art numérique", img: "🖥️", parentId: "visualarts" },
        ],
      },
      {
        id: "music",
        order: 2,
        label: "Musique",
        img: "🎵",
        parentId: "arts",
        children: [
          { id: "pop", order: 1, label: "Pop", img: "🎤", parentId: "music" },
          { id: "rock", order: 2, label: "Rock", img: "🎸", parentId: "music" },
          { id: "classical", order: 3, label: "Classique", img: "🎻", parentId: "music" },
          { id: "jazz", order: 4, label: "Jazz", img: "🎷", parentId: "music" },
          { id: "electronic", order: 5, label: "Électronique", img: "🎧", parentId: "music" },
        ],
      },
      {
        id: "cinema",
        order: 3,
        label: "Cinéma & Séries",
        img: "🎬",
        parentId: "arts",
        children: [
          { id: "reviews", order: 1, label: "Critiques", img: "⭐", parentId: "cinema" },
          { id: "directors", order: 2, label: "Réalisateurs", img: "🎥", parentId: "cinema" },
          { id: "screenwriting", order: 3, label: "Scénario", img: "📝", parentId: "cinema" },
          { id: "streaming", order: 4, label: "Plateformes", img: "📺", parentId: "cinema" },
        ],
      },
      {
        id: "literature",
        order: 4,
        label: "Littérature",
        img: "📚",
        parentId: "arts",
        children: [
          { id: "novels", order: 1, label: "Romans", img: "📖", parentId: "literature" },
          { id: "poetry", order: 2, label: "Poésie", img: "🖋️", parentId: "literature" },
          { id: "essays", order: 3, label: "Essais", img: "📜", parentId: "literature" },
          { id: "sf", order: 4, label: "Science-fiction", img: "👽", parentId: "literature" },
          { id: "fantasy", order: 5, label: "Fantasy", img: "🐉", parentId: "literature" },
        ],
      },
      {
        id: "theatre",
        order: 5,
        label: "Théâtre & Danse",
        img: "🎭",
        parentId: "arts",
        children: [
          { id: "plays", order: 1, label: "Pièces", img: "🎭", parentId: "theatre" },
          { id: "ballet", order: 2, label: "Ballet", img: "🩰", parentId: "theatre" },
          { id: "comedy", order: 3, label: "Humour", img: "😂", parentId: "theatre" },
        ],
      },
    ],
  },
  {
    id: "business",
    order: 5,
    label: "Business & Finance",
    img: "💼",
    children: [
      {
        id: "entrepreneurship",
        order: 1,
        label: "Entrepreneuriat",
        img: "🚀",
        parentId: "business",
        children: [
          { id: "startups", order: 1, label: "Startups", img: "💡", parentId: "entrepreneurship" },
          { id: "fundraising", order: 2, label: "Levée de fonds", img: "💰", parentId: "entrepreneurship" },
          { id: "businessplans", order: 3, label: "Business plans", img: "📋", parentId: "entrepreneurship" },
          { id: "freelance", order: 4, label: "Freelance", img: "🧑‍💻", parentId: "entrepreneurship" },
        ],
      },
      {
        id: "finance",
        order: 2,
        label: "Finance personnelle",
        img: "💰",
        parentId: "business",
        children: [
          { id: "budgeting", order: 1, label: "Budget", img: "📊", parentId: "finance" },
          { id: "investing", order: 2, label: "Investissements", img: "📈", parentId: "finance" },
          { id: "retirement", order: 3, label: "Retraite", img: "👴", parentId: "finance" },
          { id: "taxes", order: 4, label: "Impôts", img: "🧾", parentId: "finance" },
          { id: "crypto", order: 5, label: "Cryptomonnaies", img: "₿", parentId: "finance" },
        ],
      },
      {
        id: "marketing",
        order: 3,
        label: "Marketing & Ventes",
        img: "📢",
        parentId: "business",
        children: [
          { id: "digitalmarketing", order: 1, label: "Marketing digital", img: "📱", parentId: "marketing" },
          { id: "seo", order: 2, label: "SEO", img: "🔍", parentId: "marketing" },
          { id: "socialmedia", order: 3, label: "Réseaux sociaux", img: "📲", parentId: "marketing" },
          { id: "branding", order: 4, label: "Image de marque", img: "🏷️", parentId: "marketing" },
          { id: "ads", order: 5, label: "Publicité", img: "📺", parentId: "marketing" },
        ],
      },
      {
        id: "management",
        order: 4,
        label: "Management & RH",
        img: "👥",
        parentId: "business",
        children: [
          { id: "leadership", order: 1, label: "Leadership", img: "👔", parentId: "management" },
          { id: "recruitment", order: 2, label: "Recrutement", img: "📝", parentId: "management" },
          { id: "culture", order: 3, label: "Culture d'entreprise", img: "🏢", parentId: "management" },
          { id: "productivity", order: 4, label: "Productivité", img: "⏳", parentId: "management" },
        ],
      },
      {
        id: "economics",
        order: 5,
        label: "Économie",
        img: "📉",
        parentId: "business",
        children: [
          { id: "macro", order: 1, label: "Macroéconomie", img: "🌍", parentId: "economics" },
          { id: "micro", order: 2, label: "Microéconomie", img: "🏪", parentId: "economics" },
          { id: "global", order: 3, label: "Économie mondiale", img: "🌐", parentId: "economics" },
        ],
      },
    ],
  },
  {
    id: "education",
    order: 6,
    label: "Éducation & Carrière",
    img: "📚",
    children: [
      {
        id: "school",
        order: 1,
        label: "Vie scolaire",
        img: "🏫",
        parentId: "education",
        children: [
          { id: "tips", order: 1, label: "Méthodes de travail", img: "✏️", parentId: "school" },
          { id: "exams", order: 2, label: "Examens", img: "📝", parentId: "school" },
          { id: "college", order: 3, label: "Études supérieures", img: "🎓", parentId: "school" },
        ],
      },
      {
        id: "languages",
        order: 2,
        label: "Langues",
        img: "🗣️",
        parentId: "education",
        children: [
          { id: "english", order: 1, label: "Anglais", img: "🇬🇧", parentId: "languages" },
          { id: "french", order: 2, label: "Français", img: "🇫🇷", parentId: "languages" },
          { id: "spanish", order: 3, label: "Espagnol", img: "🇪🇸", parentId: "languages" },
          { id: "german", order: 4, label: "Allemand", img: "🇩🇪", parentId: "languages" },
          { id: "chinese", order: 5, label: "Chinois", img: "🇨🇳", parentId: "languages" },
        ],
      },
      {
        id: "career",
        order: 3,
        label: "Développement de carrière",
        img: "💼",
        parentId: "education",
        children: [
          { id: "cv", order: 1, label: "CV & lettres", img: "📄", parentId: "career" },
          { id: "interviews", order: 2, label: "Entretiens", img: "🤝", parentId: "career" },
          { id: "jobs", order: 3, label: "Métiers", img: "🧑‍💼", parentId: "career" },
          { id: "internships", order: 4, label: "Stages", img: "📋", parentId: "career" },
        ],
      },
      {
        id: "elearning",
        order: 4,
        label: "E-learning",
        img: "💻",
        parentId: "education",
        children: [
          { id: "moocs", order: 1, label: "MOOC", img: "🎓", parentId: "elearning" },
          { id: "tutorials", order: 2, label: "Tutoriels", img: "📹", parentId: "elearning" },
          { id: "platforms", order: 3, label: "Plateformes", img: "🖥️", parentId: "elearning" },
        ],
      },
    ],
  },
  {
    id: "lifestyle",
    order: 7,
    label: "Lifestyle & Développement personnel",
    img: "🌟",
    children: [
      {
        id: "personaldev",
        order: 1,
        label: "Développement personnel",
        img: "🌱",
        parentId: "lifestyle",
        children: [
          { id: "habits", order: 1, label: "Habitudes", img: "⏰", parentId: "personaldev" },
          { id: "goals", order: 2, label: "Objectifs", img: "🎯", parentId: "personaldev" },
          { id: "motivation", order: 3, label: "Motivation", img: "💪", parentId: "personaldev" },
          { id: "confidence", order: 4, label: "Confiance en soi", img: "✨", parentId: "personaldev" },
        ],
      },
      {
        id: "relationships",
        order: 2,
        label: "Relations & Famille",
        img: "👪",
        parentId: "lifestyle",
        children: [
          { id: "couple", order: 1, label: "Couple", img: "💑", parentId: "relationships" },
          { id: "friends", order: 2, label: "Amitiés", img: "👥", parentId: "relationships" },
          { id: "parenting", order: 3, label: "Parentalité", img: "👶", parentId: "relationships" },
          { id: "communication", order: 4, label: "Communication", img: "💬", parentId: "relationships" },
        ],
      },
      {
        id: "home",
        order: 3,
        label: "Maison & Décoration",
        img: "🏡",
        parentId: "lifestyle",
        children: [
          { id: "decor", order: 1, label: "Décoration", img: "🛋️", parentId: "home" },
          { id: "diy", order: 2, label: "DIY", img: "🛠️", parentId: "home" },
          { id: "gardening", order: 3, label: "Jardinage", img: "🌿", parentId: "home" },
          { id: "cleaning", order: 4, label: "Nettoyage", img: "🧹", parentId: "home" },
        ],
      },
      {
        id: "hobbies",
        order: 4,
        label: "Loisirs & Passions",
        img: "🎨",
        parentId: "lifestyle",
        children: [
          { id: "reading", order: 1, label: "Lecture", img: "📖", parentId: "hobbies" },
          { id: "gaming", order: 2, label: "Jeux vidéo", img: "🎮", parentId: "hobbies" },
          { id: "collecting", order: 3, label: "Collection", img: "🪙", parentId: "hobbies" },
          { id: "boardgames", order: 4, label: "Jeux de société", img: "🎲", parentId: "hobbies" },
        ],
      },
      {
        id: "pets",
        order: 5,
        label: "Animaux de compagnie",
        img: "🐾",
        parentId: "lifestyle",
        children: [
          { id: "dogs", order: 1, label: "Chiens", img: "🐕", parentId: "pets" },
          { id: "cats", order: 2, label: "Chats", img: "🐈", parentId: "pets" },
          { id: "fish", order: 3, label: "Poissons", img: "🐠", parentId: "pets" },
          { id: "birds", order: 4, label: "Oiseaux", img: "🦜", parentId: "pets" },
          { id: "smallpets", order: 5, label: "NAC", img: "🐹", parentId: "pets" },
        ],
      },
    ],
  },
  {
    id: "travel",
    order: 8,
    label: "Voyages & Tourisme",
    img: "✈️",
    children: [
      {
        id: "destinations",
        order: 1,
        label: "Destinations",
        img: "🗺️",
        parentId: "travel",
        children: [
          { id: "europe", order: 1, label: "Europe", img: "🇪🇺", parentId: "destinations" },
          { id: "asia", order: 2, label: "Asie", img: "🇯🇵", parentId: "destinations" },
          { id: "americas", order: 3, label: "Amériques", img: "🌎", parentId: "destinations" },
          { id: "africa", order: 4, label: "Afrique", img: "🌍", parentId: "destinations" },
          { id: "oceania", order: 5, label: "Océanie", img: "🇦🇺", parentId: "destinations" },
          { id: "antarctica", order: 6, label: "Antarctique", img: "❄️", parentId: "destinations" },
        ],
      },
      {
        id: "tips-travel",
        order: 2,
        label: "Conseils voyage",
        img: "💡",
        parentId: "travel",
        children: [
          { id: "budget-travel", order: 1, label: "Voyager pas cher", img: "💰", parentId: "tips-travel" },
          { id: "packing", order: 2, label: "Bagages", img: "🧳", parentId: "tips-travel" },
          { id: "safety", order: 3, label: "Sécurité", img: "🛡️", parentId: "tips-travel" },
          { id: "solo", order: 4, label: "Voyage en solo", img: "🧑", parentId: "tips-travel" },
          { id: "family", order: 5, label: "Voyage en famille", img: "👪", parentId: "tips-travel" },
        ],
      },
      {
        id: "adventure",
        order: 3,
        label: "Aventures & Plein air",
        img: "🏔️",
        parentId: "travel",
        children: [
          { id: "hiking", order: 1, label: "Randonnée", img: "🥾", parentId: "adventure" },
          { id: "camping", order: 2, label: "Camping", img: "🏕️", parentId: "adventure" },
          { id: "roadtrip", order: 3, label: "Road trip", img: "🚗", parentId: "adventure" },
          { id: "backpacking", order: 4, label: "Backpacking", img: "🎒", parentId: "adventure" },
        ],
      },
      {
        id: "cultural",
        order: 4,
        label: "Tourisme culturel",
        img: "🏛️",
        parentId: "travel",
        children: [
          { id: "heritage", order: 1, label: "Patrimoine", img: "🏰", parentId: "cultural" },
          { id: "museums", order: 2, label: "Musées", img: "🖼️", parentId: "cultural" },
          { id: "festivals", order: 3, label: "Festivals", img: "🎉", parentId: "cultural" },
        ],
      },
    ],
  },
  {
    id: "food",
    order: 9,
    label: "Cuisine & Gastronomie",
    img: "🍳",
    children: [
      {
        id: "recipes",
        order: 1,
        label: "Recettes",
        img: "📝",
        parentId: "food",
        children: [
          { id: "starters", order: 1, label: "Entrées", img: "🥗", parentId: "recipes" },
          { id: "mains", order: 2, label: "Plats", img: "🍲", parentId: "recipes" },
          { id: "desserts", order: 3, label: "Desserts", img: "🍰", parentId: "recipes" },
          { id: "vegetarian", order: 4, label: "Végétarien", img: "🥕", parentId: "recipes" },
          { id: "vegan", order: 5, label: "Vegan", img: "🌱", parentId: "recipes" },
          { id: "glutenfree", order: 6, label: "Sans gluten", img: "🌾", parentId: "recipes" },
        ],
      },
      {
        id: "worldcuisine",
        order: 2,
        label: "Cuisines du monde",
        img: "🌍",
        parentId: "food",
        children: [
          { id: "italian", order: 1, label: "Italienne", img: "🇮🇹", parentId: "worldcuisine" },
          { id: "french", order: 2, label: "Française", img: "🇫🇷", parentId: "worldcuisine" },
          { id: "japanese", order: 3, label: "Japonaise", img: "🇯🇵", parentId: "worldcuisine" },
          { id: "mexican", order: 4, label: "Mexicaine", img: "🇲🇽", parentId: "worldcuisine" },
          { id: "indian", order: 5, label: "Indienne", img: "🇮🇳", parentId: "worldcuisine" },
          { id: "chinese", order: 6, label: "Chinoise", img: "🇨🇳", parentId: "worldcuisine" },
        ],
      },
      {
        id: "techniques",
        order: 3,
        label: "Techniques culinaires",
        img: "🔪",
        parentId: "food",
        children: [
          { id: "baking", order: 1, label: "Pâtisserie", img: "🥐", parentId: "techniques" },
          { id: "knife", order: 2, label: "Découpe", img: "🔪", parentId: "techniques" },
          { id: "cookingmethods", order: 3, label: "Cuissons", img: "🔥", parentId: "techniques" },
          { id: "fermentation", order: 4, label: "Fermentation", img: "🥒", parentId: "techniques" },
        ],
      },
      {
        id: "wine",
        order: 4,
        label: "Œnologie & Boissons",
        img: "🍷",
        parentId: "food",
        children: [
          { id: "wine", order: 1, label: "Vin", img: "🍷", parentId: "wine" },
          { id: "beer", order: 2, label: "Bière", img: "🍺", parentId: "wine" },
          { id: "cocktails", order: 3, label: "Cocktails", img: "🍸", parentId: "wine" },
          { id: "coffee", order: 4, label: "Café", img: "☕", parentId: "wine" },
          { id: "tea", order: 5, label: "Thé", img: "🍵", parentId: "wine" },
        ],
      },
    ],
  },
  {
    id: "sports",
    order: 10,
    label: "Sports & Loisirs sportifs",
    img: "⚽",
    children: [
      {
        id: "teamsports",
        order: 1,
        label: "Sports collectifs",
        img: "🏀",
        parentId: "sports",
        children: [
          { id: "football", order: 1, label: "Football", img: "⚽", parentId: "teamsports" },
          { id: "basketball", order: 2, label: "Basket-ball", img: "🏀", parentId: "teamsports" },
          { id: "volleyball", order: 3, label: "Volley-ball", img: "🏐", parentId: "teamsports" },
          { id: "rugby", order: 4, label: "Rugby", img: "🏉", parentId: "teamsports" },
          { id: "handball", order: 5, label: "Handball", img: "🤾", parentId: "teamsports" },
        ],
      },
      {
        id: "individual",
        order: 2,
        label: "Sports individuels",
        img: "🏃",
        parentId: "sports",
        children: [
          { id: "tennis", order: 1, label: "Tennis", img: "🎾", parentId: "individual" },
          { id: "golf", order: 2, label: "Golf", img: "🏌️", parentId: "individual" },
          { id: "cycling", order: 3, label: "Cyclisme", img: "🚴", parentId: "individual" },
          { id: "swimming", order: 4, label: "Natation", img: "🏊", parentId: "individual" },
          { id: "athletics", order: 5, label: "Athlétisme", img: "🏃", parentId: "individual" },
          { id: "boxing", order: 6, label: "Boxe", img: "🥊", parentId: "individual" },
        ],
      },
      {
        id: "outdoor",
        order: 3,
        label: "Sports de pleine nature",
        img: "🏔️",
        parentId: "sports",
        children: [
          { id: "climbing", order: 1, label: "Escalade", img: "🧗", parentId: "outdoor" },
          { id: "ski", order: 2, label: "Ski", img: "⛷️", parentId: "outdoor" },
          { id: "surf", order: 3, label: "Surf", img: "🏄", parentId: "outdoor" },
          { id: "kayak", order: 4, label: "Kayak", img: "🛶", parentId: "outdoor" },
          { id: "paragliding", order: 5, label: "Parapente", img: "🪂", parentId: "outdoor" },
        ],
      },
      {
        id: "esports",
        order: 4,
        label: "Esports",
        img: "🎮",
        parentId: "sports",
        children: [
          { id: "lol", order: 1, label: "League of Legends", img: "🕹️", parentId: "esports" },
          { id: "csgo", order: 2, label: "CS:GO", img: "🔫", parentId: "esports" },
          { id: "valorant", order: 3, label: "Valorant", img: "🔮", parentId: "esports" },
          { id: "dota2", order: 4, label: "Dota 2", img: "🛡️", parentId: "esports" },
        ],
      },
    ],
  },
  {
    id: "society",
    order: 11,
    label: "Société & Politique",
    img: "🏛️",
    children: [
      {
        id: "politics",
        order: 1,
        label: "Politique",
        img: "🗳️",
        parentId: "society",
        children: [
          { id: "international", order: 1, label: "International", img: "🌐", parentId: "politics" },
          { id: "national", order: 2, label: "Nationale", img: "🇫🇷", parentId: "politics" },
          { id: "elections", order: 3, label: "Élections", img: "🗳️", parentId: "politics" },
          { id: "geopolitics", order: 4, label: "Géopolitique", img: "🌍", parentId: "politics" },
        ],
      },
      {
        id: "law",
        order: 2,
        label: "Droit & Justice",
        img: "⚖️",
        parentId: "society",
        children: [
          { id: "civillaw", order: 1, label: "Droit civil", img: "📜", parentId: "law" },
          { id: "criminallaw", order: 2, label: "Droit pénal", img: "🔨", parentId: "law" },
          { id: "businesslaw", order: 3, label: "Droit des affaires", img: "💼", parentId: "law" },
          { id: "humanrights", order: 4, label: "Droits humains", img: "🕊️", parentId: "law" },
        ],
      },
      {
        id: "economy-society",
        order: 3,
        label: "Économie sociale",
        img: "📊",
        parentId: "society",
        children: [
          { id: "inequality", order: 1, label: "Inégalités", img: "⚖️", parentId: "economy-society" },
          { id: "employment", order: 2, label: "Emploi", img: "💼", parentId: "economy-society" },
          { id: "socialsecurity", order: 3, label: "Protection sociale", img: "🛡️", parentId: "economy-society" },
          { id: "poverty", order: 4, label: "Pauvreté", img: "🤝", parentId: "economy-society" },
        ],
      },
      {
        id: "environmental",
        order: 4,
        label: "Environnement",
        img: "🌿",
        parentId: "society",
        children: [
          { id: "climate", order: 1, label: "Climat", img: "🌍", parentId: "environmental" },
          { id: "biodiversity", order: 2, label: "Biodiversité", img: "🦋", parentId: "environmental" },
          { id: "pollution", order: 3, label: "Pollution", img: "🏭", parentId: "environmental" },
          { id: "renewable", order: 4, label: "Énergies renouvelables", img: "☀️", parentId: "environmental" },
          { id: "sustainability", order: 5, label: "Développement durable", img: "♻️", parentId: "environmental" },
        ],
      },
    ],
  },
  {
    id: "history",
    order: 12,
    label: "Histoire & Patrimoine",
    img: "🏺",
    children: [
      {
        id: "ancient",
        order: 1,
        label: "Histoire ancienne",
        img: "🏛️",
        parentId: "history",
        children: [
          { id: "egypt", order: 1, label: "Égypte", img: "🛕", parentId: "ancient" },
          { id: "greece", order: 2, label: "Grèce", img: "🏺", parentId: "ancient" },
          { id: "rome", order: 3, label: "Rome", img: "🏛️", parentId: "ancient" },
          { id: "meso", order: 4, label: "Mésopotamie", img: "🏜️", parentId: "ancient" },
        ],
      },
      {
        id: "medieval",
        order: 2,
        label: "Moyen Âge",
        img: "🏰",
        parentId: "history",
        children: [
          { id: "feudalism", order: 1, label: "Féodalité", img: "⚔️", parentId: "medieval" },
          { id: "crusades", order: 2, label: "Croisades", img: "✝️", parentId: "medieval" },
          { id: "castles", order: 3, label: "Châteaux", img: "🏰", parentId: "medieval" },
        ],
      },
      {
        id: "modern",
        order: 3,
        label: "Histoire moderne",
        img: "🎩",
        parentId: "history",
        children: [
          { id: "renaissance", order: 1, label: "Renaissance", img: "🎨", parentId: "modern" },
          { id: "revolutions", order: 2, label: "Révolutions", img: "🗽", parentId: "modern" },
          { id: "ww1", order: 3, label: "Première Guerre mondiale", img: "🪖", parentId: "modern" },
          { id: "ww2", order: 4, label: "Seconde Guerre mondiale", img: "🎖️", parentId: "modern" },
        ],
      },
      {
        id: "contemporary",
        order: 4,
        label: "Histoire contemporaine",
        img: "📰",
        parentId: "history",
        children: [
          { id: "coldwar", order: 1, label: "Guerre froide", img: "☭", parentId: "contemporary" },
          { id: "decolonization", order: 2, label: "Décolonisation", img: "🌍", parentId: "contemporary" },
          { id: "21st", order: 3, label: "XXIe siècle", img: "📱", parentId: "contemporary" },
        ],
      },
    ],
  },
  {
    id: "philosophy",
    order: 13,
    label: "Philosophie & Spiritualité",
    img: "🤔",
    children: [
      {
        id: "philo",
        order: 1,
        label: "Philosophie",
        img: "📜",
        parentId: "philosophy",
        children: [
          { id: "ethics", order: 1, label: "Éthique", img: "⚖️", parentId: "philo" },
          { id: "metaphysics", order: 2, label: "Métaphysique", img: "🌀", parentId: "philo" },
          { id: "epistemology", order: 3, label: "Épistémologie", img: "🧠", parentId: "philo" },
          { id: "logic", order: 4, label: "Logique", img: "🔍", parentId: "philo" },
          { id: "ancientphilo", order: 5, label: "Philo antique", img: "🏛️", parentId: "philo" },
        ],
      },
      {
        id: "religion",
        order: 2,
        label: "Religions",
        img: "🕊️",
        parentId: "philosophy",
        children: [
          { id: "christianity", order: 1, label: "Christianisme", img: "✝️", parentId: "religion" },
          { id: "islam", order: 2, label: "Islam", img: "☪️", parentId: "religion" },
          { id: "judaism", order: 3, label: "Judaïsme", img: "✡️", parentId: "religion" },
          { id: "buddhism", order: 4, label: "Bouddhisme", img: "☸️", parentId: "religion" },
          { id: "hinduism", order: 5, label: "Hindouisme", img: "🕉️", parentId: "religion" },
        ],
      },
      {
        id: "spirituality",
        order: 3,
        label: "Spiritualité",
        img: "✨",
        parentId: "philosophy",
        children: [
          { id: "meditation", order: 1, label: "Méditation", img: "🧘", parentId: "spirituality" },
          { id: "esotericism", order: 2, label: "Ésotérisme", img: "🔮", parentId: "spirituality" },
          { id: "astrology", order: 3, label: "Astrologie", img: "♈", parentId: "spirituality" },
          { id: "tarot", order: 4, label: "Tarot", img: "🃏", parentId: "spirituality" },
        ],
      },
    ],
  },
  {
    id: "parenting",
    order: 14,
    label: "Parentalité & Famille",
    img: "👨‍👩‍👧‍👦",
    children: [
      {
        id: "pregnancy",
        order: 1,
        label: "Grossesse & Naissance",
        img: "🤰",
        parentId: "parenting",
        children: [
          { id: "pregnancy", order: 1, label: "Grossesse", img: "🤰", parentId: "pregnancy" },
          { id: "birth", order: 2, label: "Accouchement", img: "👶", parentId: "pregnancy" },
          { id: "postpartum", order: 3, label: "Post-partum", img: "🤱", parentId: "pregnancy" },
        ],
      },
      {
        id: "baby",
        order: 2,
        label: "Bébé (0-3 ans)",
        img: "🍼",
        parentId: "parenting",
        children: [
          { id: "feeding", order: 1, label: "Alimentation", img: "🥛", parentId: "baby" },
          { id: "sleep", order: 2, label: "Sommeil", img: "😴", parentId: "baby" },
          { id: "development", order: 3, label: "Développement", img: "📈", parentId: "baby" },
          { id: "health", order: 4, label: "Santé", img: "🩺", parentId: "baby" },
        ],
      },
      {
        id: "child",
        order: 3,
        label: "Enfant (3-12 ans)",
        img: "🧒",
        parentId: "parenting",
        children: [
          { id: "education", order: 1, label: "Éducation", img: "📚", parentId: "child" },
          { id: "activities", order: 2, label: "Activités", img: "🎨", parentId: "child" },
          { id: "psychology", order: 3, label: "Psychologie", img: "🧠", parentId: "child" },
          { id: "school", order: 4, label: "École", img: "🏫", parentId: "child" },
        ],
      },
      {
        id: "teen",
        order: 4,
        label: "Adolescent",
        img: "🧑",
        parentId: "parenting",
        children: [
          { id: "communication", order: 1, label: "Communication", img: "💬", parentId: "teen" },
          { id: "autonomy", order: 2, label: "Autonomie", img: "🕊️", parentId: "teen" },
          { id: "screen", order: 3, label: "Écrans", img: "📱", parentId: "teen" },
          { id: "peerpressure", order: 4, label: "Pression sociale", img: "👥", parentId: "teen" },
        ],
      },
    ],
  },
  {
    id: "diy",
    order: 15,
    label: "DIY & Bricolage",
    img: "🛠️",
    children: [
      {
        id: "woodworking",
        order: 1,
        label: "Travail du bois",
        img: "🪵",
        parentId: "diy",
        children: [
          { id: "furniture", order: 1, label: "Meubles", img: "🪑", parentId: "woodworking" },
          { id: "carving", order: 2, label: "Sculpture", img: "🗿", parentId: "woodworking" },
          { id: "joinery", order: 3, label: "Menuiserie", img: "🔨", parentId: "woodworking" },
        ],
      },
      {
        id: "repair",
        order: 2,
        label: "Réparation & Entretien",
        img: "🔧",
        parentId: "diy",
        children: [
          { id: "plumbing", order: 1, label: "Plomberie", img: "🚰", parentId: "repair" },
          { id: "electricity", order: 2, label: "Électricité", img: "⚡", parentId: "repair" },
          { id: "appliances", order: 3, label: "Électroménager", img: "🧺", parentId: "repair" },
          { id: "automotive", order: 4, label: "Voiture", img: "🚗", parentId: "repair" },
        ],
      },
      {
        id: "crafts",
        order: 3,
        label: "Arts créatifs",
        img: "🎨",
        parentId: "diy",
        children: [
          { id: "knitting", order: 1, label: "Tricot", img: "🧶", parentId: "crafts" },
          { id: "sewing", order: 2, label: "Couture", img: "🪡", parentId: "crafts" },
          { id: "pottery", order: 3, label: "Poterie", img: "🏺", parentId: "crafts" },
          { id: "jewelry", order: 4, label: "Bijoux", img: "💍", parentId: "crafts" },
          { id: "papercraft", order: 5, label: "Papier", img: "📄", parentId: "crafts" },
        ],
      },
    ],
  },
  {
    id: "automotive",
    order: 16,
    label: "Automobile & Mobilité",
    img: "🚗",
    children: [
      {
        id: "cars",
        order: 1,
        label: "Voitures",
        img: "🚘",
        parentId: "automotive",
        children: [
          { id: "reviews-auto", order: 1, label: "Essais", img: "📝", parentId: "cars" },
          { id: "maintenance", order: 2, label: "Entretien", img: "🔧", parentId: "cars" },
          { id: "electric", order: 3, label: "Électriques", img: "⚡", parentId: "cars" },
          { id: "hybrid", order: 4, label: "Hybrides", img: "🔋", parentId: "cars" },
          { id: "classic", order: 5, label: "Anciennes", img: "🕰️", parentId: "cars" },
        ],
      },
      {
        id: "motorcycles",
        order: 2,
        label: "Motos",
        img: "🏍️",
        parentId: "automotive",
        children: [
          { id: "sportbike", order: 1, label: "Sportives", img: "🏁", parentId: "motorcycles" },
          { id: "cruiser", order: 2, label: "Cruisers", img: "🛵", parentId: "motorcycles" },
          { id: "offroad", order: 3, label: "Tout-terrain", img: "🏞️", parentId: "motorcycles" },
        ],
      },
      {
        id: "sustainable",
        order: 3,
        label: "Mobilité durable",
        img: "🚲",
        parentId: "automotive",
        children: [
          { id: "bikes", order: 1, label: "Vélos", img: "🚲", parentId: "sustainable" },
          { id: "scooters", order: 2, label: "Trottinettes", img: "🛴", parentId: "sustainable" },
          { id: "publictransport", order: 3, label: "Transports en commun", img: "🚆", parentId: "sustainable" },
        ],
      },
    ],
  },
  {
    id: "gaming",
    order: 17,
    label: "Jeux vidéo",
    img: "🎮",
    children: [
      {
        id: "platforms",
        order: 1,
        label: "Plates-formes",
        img: "🕹️",
        parentId: "gaming",
        children: [
          { id: "pc", order: 1, label: "PC", img: "🖥️", parentId: "platforms" },
          { id: "playstation", order: 2, label: "PlayStation", img: "🎮", parentId: "platforms" },
          { id: "xbox", order: 3, label: "Xbox", img: "🎮", parentId: "platforms" },
          { id: "nintendo", order: 4, label: "Nintendo", img: "🕹️", parentId: "platforms" },
          { id: "mobile", order: 5, label: "Mobile", img: "📱", parentId: "platforms" },
        ],
      },
      {
        id: "genres",
        order: 2,
        label: "Genres",
        img: "🏷️",
        parentId: "gaming",
        children: [
          { id: "rpg", order: 1, label: "RPG", img: "⚔️", parentId: "genres" },
          { id: "fps", order: 2, label: "FPS", img: "🔫", parentId: "genres" },
          { id: "adventure", order: 3, label: "Aventure", img: "🗺️", parentId: "genres" },
          { id: "strategy", order: 4, label: "Stratégie", img: "♟️", parentId: "genres" },
          { id: "simulation", order: 5, label: "Simulation", img: "✈️", parentId: "genres" },
          { id: "sports", order: 6, label: "Sport", img: "⚽", parentId: "genres" },
        ],
      },
      {
        id: "gaming-culture",
        order: 3,
        label: "Culture vidéoludique",
        img: "👾",
        parentId: "gaming",
        children: [
          { id: "esports-news", order: 1, label: "Esports", img: "🏆", parentId: "gaming-culture" },
          { id: "streaming", order: 2, label: "Streaming", img: "📺", parentId: "gaming-culture" },
          { id: "cosplay", order: 3, label: "Cosplay", img: "🎭", parentId: "gaming-culture" },
          { id: "retro", order: 4, label: "Rétrogaming", img: "🕹️", parentId: "gaming-culture" },
        ],
      },
    ],
  },
  {
    id: "news",
    order: 18,
    label: "Actualités & Médias",
    img: "📰",
    children: [
      {
        id: "current",
        order: 1,
        label: "Actualité générale",
        img: "📡",
        parentId: "news",
        children: [
          { id: "france", order: 1, label: "France", img: "🇫🇷", parentId: "current" },
          { id: "world", order: 2, label: "Monde", img: "🌍", parentId: "current" },
          { id: "economy", order: 3, label: "Économie", img: "📈", parentId: "current" },
          { id: "society-news", order: 4, label: "Société", img: "👥", parentId: "current" },
        ],
      },
      {
        id: "tech-news",
        order: 2,
        label: "Tech & Sciences",
        img: "🔬",
        parentId: "news",
        children: [
          { id: "gadgets", order: 1, label: "Gadgets", img: "📱", parentId: "tech-news" },
          { id: "discoveries", order: 2, label: "Découvertes", img: "🧪", parentId: "tech-news" },
          { id: "innovation", order: 3, label: "Innovations", img: "💡", parentId: "tech-news" },
        ],
      },
      {
        id: "entertainment-news",
        order: 3,
        label: "Divertissement",
        img: "🎬",
        parentId: "news",
        children: [
          { id: "celebrities", order: 1, label: "People", img: "⭐", parentId: "entertainment-news" },
          { id: "movies", order: 2, label: "Cinéma", img: "🎥", parentId: "entertainment-news" },
          { id: "music-news", order: 3, label: "Musique", img: "🎵", parentId: "entertainment-news" },
          { id: "tv", order: 4, label: "Télévision", img: "📺", parentId: "entertainment-news" },
        ],
      },
    ],
  },
  {
    id: "photography",
    order: 19,
    label: "Photographie & Vidéo",
    img: "📷",
    children: [
      {
        id: "photo-basics",
        order: 1,
        label: "Bases de la photo",
        img: "📸",
        parentId: "photography",
        children: [
          { id: "composition", order: 1, label: "Composition", img: "🖼️", parentId: "photo-basics" },
          { id: "lighting", order: 2, label: "Lumière", img: "💡", parentId: "photo-basics" },
          { id: "equipment", order: 3, label: "Matériel", img: "📷", parentId: "photo-basics" },
          { id: "editing", order: 4, label: "Retouche", img: "🎨", parentId: "photo-basics" },
        ],
      },
      {
        id: "genres-photo",
        order: 2,
        label: "Genres photographiques",
        img: "🏞️",
        parentId: "photography",
        children: [
          { id: "portrait", order: 1, label: "Portrait", img: "🧑", parentId: "genres-photo" },
          { id: "landscape", order: 2, label: "Paysage", img: "🏔️", parentId: "genres-photo" },
          { id: "street", order: 3, label: "Street", img: "🏙️", parentId: "genres-photo" },
          { id: "macro", order: 4, label: "Macro", img: "🔬", parentId: "genres-photo" },
          { id: "wildlife", order: 5, label: "Animalière", img: "🦁", parentId: "genres-photo" },
        ],
      },
      {
        id: "video",
        order: 3,
        label: "Vidéo & Montage",
        img: "🎥",
        parentId: "photography",
        children: [
          { id: "filmmaking", order: 1, label: "Réalisation", img: "🎬", parentId: "video" },
          { id: "editing-video", order: 2, label: "Montage", img: "✂️", parentId: "video" },
          { id: "youtube", order: 3, label: "YouTube", img: "▶️", parentId: "video" },
          { id: "drone", order: 4, label: "Drone", img: "🛸", parentId: "video" },
        ],
      },
    ],
  },
  {
    id: "writing",
    order: 20,
    label: "Écriture & Création littéraire",
    img: "✍️",
    children: [
      {
        id: "creative-writing",
        order: 1,
        label: "Écriture créative",
        img: "🖋️",
        parentId: "writing",
        children: [
          { id: "fiction", order: 1, label: "Fiction", img: "📖", parentId: "creative-writing" },
          { id: "poetry", order: 2, label: "Poésie", img: "🕊️", parentId: "creative-writing" },
          { id: "script", order: 3, label: "Scénario", img: "🎬", parentId: "creative-writing" },
          { id: "prompts", order: 4, label: "Exercices", img: "📝", parentId: "creative-writing" },
        ],
      },
      {
        id: "blogging",
        order: 2,
        label: "Blogging & Content",
        img: "📱",
        parentId: "writing",
        children: [
          { id: "copywriting", order: 1, label: "Copywriting", img: "✒️", parentId: "blogging" },
          { id: "seo-writing", order: 2, label: "SEO", img: "🔍", parentId: "blogging" },
          { id: "storytelling", order: 3, label: "Storytelling", img: "🎭", parentId: "blogging" },
          { id: "freelance-writing", order: 4, label: "Freelance", img: "💼", parentId: "blogging" },
        ],
      },
      {
        id: "publishing",
        order: 3,
        label: "Édition & Publication",
        img: "📚",
        parentId: "writing",
        children: [
          { id: "selfpublishing", order: 1, label: "Auto-édition", img: "📘", parentId: "publishing" },
          { id: "traditional", order: 2, label: "Édition traditionnelle", img: "🏢", parentId: "publishing" },
          { id: "bookfair", order: 3, label: "Salons", img: "🎪", parentId: "publishing" },
        ],
      },
    ],
  },
];



*/
